language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get install subversion libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
  - cd dep/thrift-0.3.0/
  - ./configure --with-py=no --with-ruby=no --with-perl=no --with-java=no --prefix=/usr/thrift
  - make
  - sudo make install
  - cmake -DThrift_INCLUDE_DIR=/usr/thrift/include -DThrift_LIB=/usr/thrift/lib .
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - czhang@cs.wisc.edu
  email:
    on_success: change
    on_failure: always
rvm:
  - 1.9.3
